"""make student profile fields nullable

Revision ID: 64784c9fb908
Revises: 0b084f5d5e10
Create Date: 2026-09-19 10:16:42.597243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64784c9fb908'
down_revision = '0b084f5d5e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('year_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('year_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
